--GA--/**
--GA-- * @brief Función asíncrona genérica para realizar peticiones planas (AJAX) al backend.
--GA-- * @param {string} opcion El nombre de la función / acción a ejecutar (ej. 'desplegar_menu').
--GA-- * @param {object} parametros Objeto con parámetros adicionales para enviar al servidor.
--GA-- * @return {Promise} Promesa que se resuelve tras actualizar la UI.
--GA-- * @pre Debe existir la constante global APP_TOKEN.
--GA-- * @post Actualiza el DOM (etiqueta <article>) con la respuesta JSON del servidor.
--GA--*/
--GA--async function fn_peticion_plana(opcion, parametros = {}) {
--GA--    let url = new URL(window.location.href);
--GA--    url.searchParams.set('opcion', opcion);
--GA--    url.searchParams.set('formato', 'json');
--GA--    
--GA--    // Agregamos el token de seguridad a todos los payloads para validación CSRF
--GA--    let bodyData = new FormData();
--GA--    if (typeof APP_TOKEN !== 'undefined') {
--GA--        bodyData.append('token', APP_TOKEN);
--GA--    }
--GA--    
--GA--    for (let key in parametros) {
--GA--        bodyData.append(key, parametros[key]);
--GA--    }
--GA--
--GA--    try {
--GA--        const respuesta = await fetch(url, {
--GA--            method: 'POST',
--GA--            body: bodyData,
--GA--            headers: {
--GA--                'X-Requested-With': 'XMLHttpRequest'
--GA--            }
--GA--        });
--GA--
--GA--        if (!respuesta.ok) {
--GA--            const errorJson = await respuesta.json();
--GA--            alert("Error de Seguridad/Servidor: " + (errorJson.error || respuesta.statusText));
--GA--            return false;
--GA--        }
--GA--
--GA--        const datos = await respuesta.json();
--GA--        
--GA--        // Arquitectura plana: solo reemplazamos el contenido visual sin recargar
--GA--        if (datos.html !== undefined) {
--GA--            const cajaContenido = document.querySelector('article');
--GA--            if (cajaContenido) {
--GA--                cajaContenido.innerHTML = datos.html;
--GA--            }
--GA--        }
--GA--        return datos;
--GA--    } catch (e) {
--GA--        console.error("Error en petición plana:", e);
--GA--        alert("Hubo un error al comunicar con el servidor.");
--GA--        return false;
--GA--    }
--GA--}
--GA--
--GA--/**
--GA-- * @brief Intercepta los clicks de navegación para usar peticiones planas en vez de recargar.
--GA-- * @param {string} opcion Acción solicitada.
--GA-- */
--GA--function navegarA(opcion) {
--GA--    fn_peticion_plana(opcion);
--GA--}
